export const rows = [
  {
    id: 1,
    name: "Ahmad Jokhadar",
    email: "Ahmad.Jokhadar@gmail.com",
    age: 30,
    phone: "+961 70 501 358",
    access: "User",
  },
  {
    id: 2,
    name: "Ali Aboulnil",
    email: "Abonnii0999@gmail.com",
    age: 12,
    phone: "+961 81 631 347",
    access: "Manager",
  },
  {
    id: 3,
    name: "Mohamad Jokhadar",
    email: "Mohamad.joe@hotmail.com",
    age: 25,
    phone: "+961 78 585 525",
    access: "Admin",
  },
  {
    id: 4,
    name: "Rania El Hajj",
    email: "rania.elhajj@gmail.com",
    age: 16,
    phone: "+961 71 425 674",
    access: "Manager",
  },
  {
    id: 5,
    name: "Leila Abou Saad",
    email: "leila.abousaad@gmail.com",
    age: 31,
    phone: "+961 71 445 118",
    access: "Manager",
  },
  {
    id: 6,
    name: "Sara Chami",
    email: "sarachami@gmail.com",
    age: 27,
    phone: "+961 76 545 648",
    access: "User",
  },
  {
    id: 7,
    name: "Khaled Rahme",
    email: "khaledrahme@gmail.com",
    age: 44,
    phone: "+961 70 124 012",
    access: "User",
  },
  {
    id: 8,
    name: "Zeina Fares",
    email: "zeinafares@gmail.com",
    age: 36,
    phone: "+961 76 444 555",
    access: "User",
  },
  {
    id: 10,
    name: "Malek Jokhadar",
    email: "malekjokhadar17@gmail.com",
    age: 19,
    phone: "+961 81 631 347",
    access: "Manager",
  },
  {
    id: 11,
    name: "Nizar Jokhadar",
    email: "NizarJokhadar@gmail.com",
    age: 53,
    phone: "+961 3 541 965",
    access: "Admin",
  },
  {
    id: 9,
    name: "Hassan Matar",
    email: "hassanmatar@gmail.com",
    age: 65,
    phone: "+961 71 555 623",
    access: "User",
  },
];
