export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registrar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    width: 44
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
  },
];
export const rows = [
  {
    id: 1,
    registrarId: "R001",
    name: "Karim Haddad",
    age: 32,
    phone: "+961 71 234 567",
    email: "karim.haddad@example.com",
    address: "Hamra Street",
    city: "Beirut",
    zipCode: "1103",
  },
  {
    id: 2,
    registrarId: "R002",
    name: "Maya Abou Nasr",
    age: 28,
    phone: "+961 3 987 654",
    email: "maya.abounasr@example.com",
    address: "Bliss Street",
    city: "Beirut",
    zipCode: "1103",
  },
  {
    id: 3,
    registrarId: "R003",
    name: "Fadi Jabbour",
    age: 45,
    phone: "+961 76 555 123",
    email: "fadi.jabbour@example.com",
    address: "Zalka Main Road",
    city: "Zalka",
    zipCode: "1201",
  },
  {
    id: 4,
    registrarId: "R004",
    name: "Rania Kassem",
    age: 38,
    phone: "+961 70 222 333",
    email: "rania.kassem@example.com",
    address: "Ras Beirut",
    city: "Beirut",
    zipCode: "1107",
  },
  {
    id: 5,
    registrarId: "R005",
    name: "Jad El Khoury",
    age: 30,
    phone: "+961 71 444 555",
    email: "jad.elkhoury@example.com",
    address: "Ain Saadeh",
    city: "Mount Lebanon",
    zipCode: "1108",
  },
  {
    id: 6,
    registrarId: "R006",
    name: "Sara Nassar",
    age: 26,
    phone: "+961 3 123 456",
    email: "sara.nassar@example.com",
    address: "Verdun Street",
    city: "Beirut",
    zipCode: "1108",
  },
  {
    id: 7,
    registrarId: "R007",
    name: "George Tannous",
    age: 42,
    phone: "+961 70 678 901",
    email: "george.tannous@example.com",
    address: "Jounieh Highway",
    city: "Jounieh",
    zipCode: "1202",
  },
  {
    id: 8,
    registrarId: "R008",
    name: "Layla Sfeir",
    age: 35,
    phone: "+961 76 321 789",
    email: "layla.sfeir@example.com",
    address: "Achrafieh",
    city: "Beirut",
    zipCode: "1104",
  },
  {
    id: 9,
    registrarId: "R009",
    name: "Hassan Chami",
    age: 50,
    phone: "+961 71 555 678",
    email: "hassan.chami@example.com",
    address: "Broummana",
    city: "Mount Lebanon",
    zipCode: "1205",
  },
  {
    id: 10,
    registrarId: "R010",
    name: "Nadine Fares",
    age: 31,
    phone: "+961 3 222 444",
    email: "nadine.fares@example.com",
    address: "Ain El Mreisseh",
    city: "Beirut",
    zipCode: "1107",
  },
  {
    id: 11,
    registrarId: "R011",
    name: "Ali Mansour",
    age: 39,
    phone: "+961 70 333 222",
    email: "ali.mansour@example.com",
    address: "Tariq El Jdideh",
    city: "Beirut",
    zipCode: "1105",
  },
  {
    id: 12,
    registrarId: "R012",
    name: "Zeina Rahme",
    age: 29,
    phone: "+961 76 654 321",
    email: "zeina.rahme@example.com",
    address: "Kaslik",
    city: "Jounieh",
    zipCode: "1203",
  },
  {
    id: 13,
    registrarId: "R013",
    name: "Michel Kanaan",
    age: 36,
    phone: "+961 71 111 999",
    email: "michel.kanaan@example.com",
    address: "Hazmieh",
    city: "Mount Lebanon",
    zipCode: "1206",
  },
  {
    id: 14,
    registrarId: "R014",
    name: "Yasmine Saab",
    age: 27,
    phone: "+961 3 987 321",
    email: "yasmine.saab@example.com",
    address: "Furn El Chebbak",
    city: "Beirut",
    zipCode: "1106",
  },
  {
    id: 15,
    registrarId: "R015",
    name: "Fouad Saad",
    age: 43,
    phone: "+961 70 432 123",
    email: "fouad.saad@example.com",
    address: "Choueifat",
    city: "Mount Lebanon",
    zipCode: "1207",
  },
];