
export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registrar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    flex: 1,
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
  },
];
export const rows = [
  {
    id: 1,
    name: "Ahmad Khalil",
    email: "ahmadkhalil@gmail.com",
    age: 35,
    phone: "+961 70 121 545",
    address: "Beshara El Khoury Street, Beirut",
    city: "Beirut",
    zipCode: "1001",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "Noura El Hajj",
    email: "nouraelhajj@gmail.com",
    age: 42,
    phone: "+961 71 314 228",
    address: "Hamra Street, Beirut",
    city: "Beirut",
    zipCode: "1103",
    registrarId: 123512,
  },
  {
    id: 3,
    name: "Hassan Tannous",
    email: "hassantannous@gmail.com",
    age: 45,
    phone: "+961 76 982 673",
    address: "Mar Mikhael, Beirut",
    city: "Beirut",
    zipCode: "2104",
    registrarId: 4132513,
  },
  {
    id: 4,
    name: "Rania Matar",
    email: "raniamatar@gmail.com",
    age: 16,
    phone: "+961 3 425 674",
    address: "Jounieh Highway, Jounieh",
    city: "Jounieh",
    zipCode: "1205",
    registrarId: 123512,
  },
  {
    id: 5,
    name: "Layla Darwish",
    email: "layladarwish@gmail.com",
    age: 31,
    phone: "+961 78 445 118",
    address: "Verdun, Beirut",
    city: "Beirut",
    zipCode: "1108",
    registrarId: 123512,
  },
  {
    id: 6,
    name: "Naji Rahme",
    email: "najirahme@gmail.com",
    age: 55,
    phone: "+961 71 545 648",
    address: "Jal El Dib, Metn",
    city: "Metn",
    zipCode: "1501",
    registrarId: 123512,
  },
  {
    id: 7,
    name: "Ali Chami",
    email: "alichami@gmail.com",
    age: 44,
    phone: "+961 70 124 012",
    address: "Furn El Chebbak, Beirut",
    city: "Beirut",
    zipCode: "1104",
    registrarId: 123512,
  },
  {
    id: 8,
    name: "Zeina Fakhry",
    email: "zeinafakhry@gmail.com",
    age: 36,
    phone: "+961 76 444 555",
    address: "Achrafieh, Beirut",
    city: "Beirut",
    zipCode: "1105",
    registrarId: 512315,
  },
  {
    id: 9,
    name: "Fouad Khoury",
    email: "fouadkhoury@gmail.com",
    age: 65,
    phone: "+961 71 555 623",
    address: "Broummana, Mount Lebanon",
    city: "Broummana",
    zipCode: "1214",
    registrarId: 928397,
  },
  {
    id: 10,
    name: "Jad Rassi",
    email: "jadrassi@gmail.com",
    age: 42,
    phone: "+961 76 444 555",
    address: "Antelias, Metn",
    city: "Antelias",
    zipCode: "1310",
    registrarId: 533215,
  },
  {
    id: 11,
    name: "Hussein Mansour",
    email: "husseinamansour@gmail.com",
    age: 11,
    phone: "+961 71 555 623",
    address: "Hadath, Beirut",
    city: "Beirut",
    zipCode: "1209",
    registrarId: 92197,
  },
];
